use filmesdb;
insert into filme (nome, ano, descricao, url_imagem) values ('Um Sonho de Liberdade', 1994, 'Dois homens presos se reúnem ao longo de vários anos, encontrando consolo e eventual redenção através de atos de decência comum.', 'https://th.bing.com/th/id/OIP.1XVb-IU7zDZSi6Wp7UhYDQHaJ4?w=134&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('O Poderoso Chefão', 1972, 'O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.', 'https://th.bing.com/th/id/OIP.5Ygc_5mn-KHXvza_HWy1CwHaLH?w=122&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Batman: O Cavaleiro das Trevas', 2008, 'Agora com a ajuda do tenente Jim Gordon e do promotor público Harvey Dent, Batman tem tudo para banir o crime de Gotham City de uma vez por todas. Mas em breve, os três serão vítimas do Coringa, que pretende lançar Gotham em uma anarquia.', 'https://th.bing.com/th/id/OIP.J9bc5aUivHPuySu_bV11_gHaLH?w=122&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('O Poderoso Chefão: Parte II', 1974, 'Em 1950, Michael Corleone, agora à frente da família, tenta expandir o negócio do crime a Las Vegas, Los Angeles e Cuba. Paralelamente, é revelada a história de Vito Corleone, e de como saiu da Sicília e chegou a Nova Iorque.', 'https://th.bing.com/th/id/OIP.rpa797OIsDT0GgqM8diBBQHaJ4?w=136&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('12 Homens e uma Sentença', 1957, 'O julgamento de um assassinato em Nova Iorque é frustrado por um único membro, cujo ceticismo força o júri a considerar cuidadosamente as evidências antes de dar o veredito.', 'https://th.bing.com/th/id/OIP.rVNya7XPvf2GcvKixWDafAHaJ4?w=136&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('O Senhor dos Anéis: O Retorno do Rei', 2003, 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam quando eles se aproximam á Montanha da Perdição com o Um Anel.', 'https://th.bing.com/th/id/OIP.QFHj3oz6EguI1quIoBkk6wHaLH?w=136&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('A Lista de Schindler', 1993, 'Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, o industrial Oskar Schindler começa a ser preocupar com seus trabalhadores judeus depois de testemunhar sua perseguição pelos nazistas.', 'https://th.bing.com/th/id/OIP.9SbFWZ5ZUZY7JgjFIx5MKQHaLH?w=136&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Pulp Fiction: Tempo de Violência', 1994, 'As vidas de dois assassinos da máfia, um boxeador, um gângster e sua esposa, e um par de bandidos se entrelaçam em quatro histórias de violência e redenção.', 'https://th.bing.com/th/id/OIP.sOueBQKXoywW37L_l4ThKQHaLH?w=136&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('O Senhor dos Anéis: A Sociedade do Anel', 2001, 'Um manso hobbit do Condado e oito companheiros partem em uma jornada para destruir o poderoso Um Anel e salvar a Terra-média das Trevas.', 'https://th.bing.com/th/id/OIP.kHySpRqe8XAx7L_4MWdWrQHaLH?w=136&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Três Homens em Conflito', 1966, 'Um impostor se junta com dois homens para encontrar fortuna num remoto cemitério.', 'https://th.bing.com/th/id/OIP.i3eD_wzdB6IuS36tykW_ggHaLH?w=136&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Oppenheimer', 2023, 'O físico J. Robert Oppenheimer trabalha com uma equipe de cientistas durante o Projeto Manhattan, levando ao desenvolvimento da bomba atômica.', 'https://th.bing.com/th/id/OIP.e9-PIMgJeWATFCvWxhf0xgHaLH?w=122&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Homem-Aranha: Através do Aranhaverso', 2023, 'Depois de se reunir com Gwen Stacy, Homem-Aranha é jogado no multiverso. Lá, o super-herói aracnídeo encontra uma numerosa equipe encarregada de proteger sua própria existência.', 'https://th.bing.com/th/id/OIP.kZ14EzLIGLD1NCmbEBDFRgHaLH?w=122&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Barbie', 2023, 'Depois de ser expulsa da Barbieland por ser uma boneca de aparência menos do que perfeita, Barbie parte para o mundo humano em busca da verdadeira felicidade.', 'https://th.bing.com/th/id/OIP.qI6fDMioOKFbQz-VX0gAnwHaLH?w=136&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('John Wick 4: Baba Yaga', 2023, 'O ex-assassino de aluguel John Wick é procurado pelo mundo todo e a recompensa por sua captura aumenta cada vez mais. Wick descobre um caminho para derrotar a Alta Cúpula, mas antes de conquistar sua liberdade, ele precisa enfrentar um novo inimigo com alianças poderosas e forças que transformam velhos amigos em inimigos.', 'https://th.bing.com/th/id/OIP.PQW7MmEEojGrRkm10bfXwQHaLH?w=136&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Guardiões da Galáxia Vol. 3', 2023, 'Peter Quill deve reunir sua equipe para defender o universo e proteger um dos seus. Se a missão não for totalmente bem-sucedida, isso pode levar ao fim dos Guardiões.', 'https://th.bing.com/th/id/OIP.kKhk3qCIOs4fsqE0puDrVwHaLH?w=122&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7');
insert into filme (nome, ano, descricao, url_imagem) values ('Assassinos da Lua das Flores', 2023, 'Os assassinatos dados a partir de circunstâncias misteriosas na década de 1920, assolando os membros da tribo Osage, acaba desencadeando uma grande investigação envolvendo o poderoso J. Edgar Hoover, considerado o primeiro diretor do FBI.', '